const cities = [
  {
    id: "lagos",
    name: "Lagos,",
    country: "Nigeria",
    population: "200 million",
    image: "/Ekoo.jpg",
  },{
    id: "tokyo",
    name: "Tokyo,",
    country: "Japan",
    population: "13.96 million",
    image: "/beijing.jpg",
  },
  {
    id: "Delhi",
    name: "Delhi,",
    country: "India",
    population: "30.29 million",
    image: "/mia.jpg",
  },
  {
    id: "shanghai",
    name: "Shanghai,",
    country: "China",
    population: "27.79 million",
    image: "/shangai.jpg",
  },
  {
    id: "sao paulo",
    name: "São Paulo,",
    country: "Brazil",
    population: "21.65 million",
    image: "/sao paulo.jpg",
  },
  {
    id: "cairo",
    name: "Cairo,",
    country: "Egypt",
    population: "20.71 million",
    image: "/cairo.jpg",
  },
  {
    id: "mumbai",
    name: "Mumbai,",
    country: "India",
    population: "20.71 million",
    image: "/zee world.avif",
  },
  {
    id: "beijing",
    name: "Beijing,",
    country: "China",
    population: "20.71 million",
    image: "/beijing.jpg",
  },
  {
    id: "mexico",
    name: "Mexico City,",
    country: "Mexico",
    population: "21.91 million",
    image: "/mexico.jpg",
  },
  {
    id: "moscow",
    name: "Moscow,",
    country: "Russia",
    population: "12.54 million",
    image: "/moscow.jpg",
  },
  {
    id: "bangkok",
    name: "Bangkok,",
    country: "Thailand",
    population: "10.78 million",
    image: "/bangkok.jpg",
  },
  {
    id: "los angeles",
    name: "Los Angeles,",
    country: "USA",
    population: "3.8 million",
    image: "/la.jpg",
  },
  {
    id: "london",
    name: "London,",
    country: "UK",
    population: "8.91 million",
    image: "/london.jpg",
  },
];

export default cities;